build:
  image: python:2.7
  environment:
    - SECRET_KEY=secret
    - DB_HOST=127.0.0.1
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_PORT=5432
  commands:
    - pip install -r requirements.txt --cache-dir pip_cache
    - python manage.py test
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
cache:
  mount:
    - pip_cache
